version: "3.1"

services:
  liquidator-main:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP=production
      - THROTTLE=1900 # Throttle not avoid rate limiting
      # Uncomment line below and specify lending market if you only want to target a single pool
      # - MARKET=4UpD2fh7xH3VP9QQaXtsS1YY3bxzWhtfpks7FatyKvdY
    secrets:
      - keypair # secret to encrypte wallet details in container

secrets:
  keypair:
    file: /run/secrets/keypair
